#!/bin/bash
# Ask for user login details

read -p 'Username: ' username
read -sp 'Password: ' password
echo

if [[ "$password" == 1234567 ]] 
then
	echo "Welcome $username"
else
	echo "Wrong password!"
fi
