#!/bin/bash

BRANCH="$(git rev-parse --abbrev-ref HEAD)"

read -p 'Enter Commit message: ' commit_message

git add . && git commit -m "$commit_message" 

if [[ "$BRANCH" == "master" || "$BRANCH" == "main" ]]
then
	git push;
	exit 1;
else
	read -p 'Enter Origin name: ' origin_name
	git push -u origin "$origin_name";
fi
